require("configs.nightfox")
require("configs.icons")
require("configs.treesitter")
require("configs.autopairs")
require("configs.bufferline")
require("configs.dashboard")
require("configs.galaxyline")
-- require("configs.lualine")
require("configs.gitsigns")
require("configs.commenter")
require("configs.nvimtree")
require("configs.telescope")
require("configs.toggleterm")
require("configs.indent")
require("configs.neoscroll")
require("configs.project")
require("configs.surround")
