#! /bin/sh
pgrep -x sxhkd >/dev/null || sxhkd &
~/.config/dunst/load.sh &
~/.config/polybar/launch.sh float &

# bspc monitor -d  爵    ﴬ   漣
bspc monitor -d         
#bspc monitor -d 一 二 三 四 五 六 七 八 九 十
# bspc config automatic_scheme spiral
bspc config border_width 0
bspc config window_gap 5
bspc config focused_border_color "#111111"
bspc config normal_border_color "#111111"
bspc config focus_follows_pointer true
# bspc config ignore_ewmh_fullscreen all
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_by_distance true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Specific settings per app
bspc rule -a Zathura state=tiled follow=on
bspc rule -a Nitrogen state=floating follow=on center=true rectangle=600x400+0+0

bspc rule -a Org.gnome.Nautilus state=floating follow=on center=true rectangle=850x500+0+0
bspc rule -a notion-app-enhanced desktop='^6' follow=off
bspc rule -a discord desktop='^8' follow=on
bspc rule -a TelegramDesktop desktop='^8' follow=on
bspc rule -a Caprine desktop='^8' follow=on
bspc rule -a pomotroid state=floating rectangle=600+503+145

bspc rule -a Gthumb state=floating follow=on center=true
bspc rule -a Font-manager state=floating follow=on center=true
